# contents of "Dockerfile.template"

FROM tensorflow/serving:2.8.0

RUN mkdir -p /models/${model_name}/${directory_to_add}
WORKDIR /models/${model_name}/${directory_to_add}

COPY ${directory_to_add} ./

ENV MODEL_NAME ${model_name}