name: Build, Deploy to GKE

on:
  push:
    branches:
      - workflow-test

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: mycluster
  GKE_REGION: asia-south1
  DEPLOYMENT_NAME: npr-od
  IMAGE: npr-od-service

jobs:
  setup-build-publish-deploy:
    name: Setup and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        
    - run: |-
        gcloud --quiet auth configure-docker
        
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Generate dockerfile
      run: ls . && sh gen-dockerfile.sh

    - name: Build
      run: |-
        ls . && docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .